config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :recipes
  resources :ingredients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    belongs_to :user
    belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :ingredient_recipes
    has_many :recipes, through: :ingredient_recipes
    has_many :users, through: :recipes
    has_many :allergies
    
    
    

     
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
    belongs_to :recipe
    belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :ingredient_recipes
    has_many :ingredients, through: :ingredient_recipes

end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :ingredient_recipes, through: :recipes
    has_many :ingredients, through: :ingredient_recipes
    has_many :allergies
    validates :name, presence: true, uniqueness: {case_sensitive: false}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredient_recipes_controller.rb
class IngredientRecipesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all 
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :find_recipe, only: [:show, :destroy, :edit]
  def index
    @recipes = Recipe.all 
  end

  def show
    
  end

  def new
    @recipe = Recipe.new
  end

  def create
    ingredient = Ingredient.find(params[:recipe][:ingredient_recipes][:ingredient_id])
    @recipe = Recipe.create(recipe_params)
    @recipe.ingredients << ingredient
    redirect_to recipe_path(@recipe)
  end

  def edit
  end

  def update
    recipe_update
  end


  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  private
  def find_recipe
    @recipe = Recipe.find(params[:id])
  end
  def recipe_params
    params.require(:recipe).permit(:name, :user_id)
  end 

  def recipe_update
    ingredient = Ingredient.find(params[:recipe][:ingredient_recipes][:ingredient_id])
    @recipe = Recipe.find_or_create_by(recipe_params)
    @recipe.ingredients << ingredient
    redirect_to recipe_path(@recipe)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :find_user, only: [:show, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if !@user.valid?
      render :new
    else
      @user.save
      redirect_to user_path(@user)
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredient_recipes_helper.rb
module IngredientRecipesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredient_recipes/index.html.erb
<h1>IngredientRecipes#index</h1>
<p>Find me in app/views/ingredient_recipes/index.html.erb</p>

app/views/ingredient_recipes/show.html.erb
<h1>IngredientRecipes#show</h1>
<p>Find me in app/views/ingredient_recipes/show.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients index page </h1>

<ul>
    <% @ingredients.each do |ing| %> 
        <li><%= link_to ing.name, ingredient_path(ing) %> -Amount of people with this allergy: <%= ing.allergies.order("user_id_count ASC").count %></li>
    <% end %> 
</ul>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<ul> 
    <% @ingredient.recipes.each do |recip| %>
        <li><%= link_to recip.name, recipe_path(recip) %></li>
    <% end %> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allergen1App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<%= form_for @recipe do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> 
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :name %>
    <%= f.fields_for :ingredient_recipes do |s|%>
        <%= s.label :ingredient%>
        <%= s.collection_select :ingredient_id, Ingredient.all, :id, :name %>
    <% end %>
    <%= f.submit "Create recipe" %> 
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes Index Page</h1>
<ul>
<% @recipes.each do |recip| %>
    <li><%= link_to recip.name, recipe_path(recip) %></li>
<% end %> 
</ul>

<%= form_with(url: "/ingredients", method: "get") do %>
    <%= label_tag(:ingredients, "Search for:") %>
    <%= text_field_tag(:ingredients) %>
    <%= submit_tag("Search")%>
  <% end %>

<%= link_to "Create a recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> 
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :name %>
    <%= f.submit "Create recipe" %> 
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<ul>
    <% @recipe.ingredients.each do |ing| %>
        <li><%= link_to ing.name, ingredient_path(ing) %></li>
    <% end %> 
</ul>

<%= form_tag recipe_path(@recipe), method: "delete" do%>
    <%= submit_tag "Delete this recipe"%>
<% end %>

app/views/shared/_error_list.html.erb
<% if @user.errors %>
    <ul>
        <% @user.errors.full_messages.each do |message|%>
            <li class="error"><%= message%></li>
        <% end %>
    </ul>
<% end %>

;kajsdf;kjadfasdfasdfa

app/views/users/index.html.erb
<h1>Who are you?</h1>

<ul>
    <% @users.each do |user|%>
        <li><%= link_to user.name, user_path(user)%></li>
    <% end %>
</ul>

<%= link_to "Create a new user", new_user_path%>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<%= render partial: "shared/error_list"%>

<%= form_for @user do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name%>
    <%= f.submit%>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.name%></h1>

<ul>
    <% @user.recipes.each do |recipe|%>
        <li><%= link_to recipe.name, recipe_path(recipe)%></li>
    <%end%>
</ul>

<%= form_tag user_path(@user), method: "delete" do%>
    <%= submit_tag "Delete this user"%>
<% end %>